---
- hosts: frontends
  tasks:
    - name: git pull sample
      git:
        repo: https://github.com/ansible/ansible-examples.git
        dest: /Users/doh/cloudnativedemo/ansible2cookbook/ch4/src/
        refspec: '+refs/pull/*:refs/heads/*'