---
- hosts: frontends
  tasks:
    - command: echo {{ item }}
      loop: [ 1, 2, 3, 4, 5, 6 ]
      when: item > 3
    - shell: "echo {{ item }}"
      loop:
        - "here"
        - "there"
      register: echo
    - name: grant a permission for each user in multiple data sources
      postgresql_user:
        name: "{{ item[0] }}"
        priv: "{{ item[1] }}.*:ALL"
        append_privs: yes
        password: "admin"
      loop: "{{ ['daniel', 'justine'] |product(['customerdb', 'preferencedb', 'referencedb'])|list }}"
