---
- hosts: frontends
  remote_user: doh
  handlers:
    - name: restart apache
      service:
        name: launchd 
        state: restarted
      listen: "restart web services"
  tasks:
    - name: restart everything
      command: echo "this task will restart the web services"
      notify: "restart web services"
