- name: "connect to network switches"
  hosts: switches
  gather_facts: no

  tasks:

    - name: define eos facts
      eos_facts:
      when: ansible_network_os == 'eos'

    - name: define ios facts
      ios_facts:
      when: ansible_network_os == 'ios'

    - name: make directory to store backup files
      file:
        path: "/tmp/backups/"
        state: directory
        recurse: yes

    - name: copy backup files only for eos devices
      copy:
        src: "{{ backup_dir }}"
        dest: "/tmp/backups/eos.bck"
      when: ansible_network_os == 'eos'